from typing import Any, Dict, Sequence, Tuple

# Shared application configuration extracted from graph_chat_app.py

DEFAULT_HOST = "0.0.0.0"
DEFAULT_PORT = 8000
DEFAULT_MODEL = "openai/gpt-4.1-mini"
DEFAULT_MAX_TOKENS = 400
OPENROUTER_BASE_URL = "https://openrouter.ai/api/v1"
SQL_ROW_LIMIT = 50
CACHE_VERSION = 3

GRAPH_CONFIG: Dict[str, Dict[str, Any]] = {
    "sales_order_headers": {
        "entity": "Sales Order",
        "id_fields": ["salesOrder"],
        "label_fields": ["salesOrder"],
        "detail_fields": ["soldToParty", "totalNetAmount", "transactionCurrency", "overallDeliveryStatus", "overallOrdReltdBillgStatus"],
        "color": "#1877f2",
        "size": 42,
    },
    "sales_order_items": {
        "entity": "Sales Order Item",
        "id_fields": ["salesOrder", "salesOrderItem"],
        "label_fields": ["salesOrder", "salesOrderItem"],
        "detail_fields": ["material", "requestedQuantity", "requestedQuantityUnit", "netAmount", "productionPlant"],
        "color": "#4f9cff",
        "size": 28,
    },
    "sales_order_schedule_lines": {
        "entity": "Schedule Line",
        "id_fields": ["salesOrder", "salesOrderItem", "scheduleLine"],
        "label_fields": ["salesOrder", "salesOrderItem", "scheduleLine"],
        "detail_fields": ["confirmedDeliveryDate", "confdOrderQtyByMatlAvailCheck", "orderQuantityUnit"],
        "color": "#84b7ff",
        "size": 20,
    },
    "outbound_delivery_headers": {
        "entity": "Delivery",
        "id_fields": ["deliveryDocument"],
        "label_fields": ["deliveryDocument"],
        "detail_fields": ["shippingPoint", "overallGoodsMovementStatus", "overallPickingStatus"],
        "color": "#0ea5a3",
        "size": 36,
    },
    "outbound_delivery_items": {
        "entity": "Delivery Item",
        "id_fields": ["deliveryDocument", "deliveryDocumentItem"],
        "label_fields": ["deliveryDocument", "deliveryDocumentItem"],
        "detail_fields": ["referenceSdDocument", "referenceSdDocumentItem", "actualDeliveryQuantity", "plant"],
        "color": "#27c2c0",
        "size": 24,
    },
    "billing_document_headers": {
        "entity": "Billing Document",
        "id_fields": ["billingDocument"],
        "label_fields": ["billingDocument"],
        "detail_fields": ["accountingDocument", "soldToParty", "totalNetAmount", "transactionCurrency", "billingDocumentIsCancelled"],
        "color": "#ef4444",
        "size": 36,
    },
    "billing_document_items": {
        "entity": "Billing Item",
        "id_fields": ["billingDocument", "billingDocumentItem"],
        "label_fields": ["billingDocument", "billingDocumentItem"],
        "detail_fields": ["material", "netAmount", "referenceSdDocument", "referenceSdDocumentItem"],
        "color": "#f87171",
        "size": 24,
    },
    "billing_document_cancellations": {
        "entity": "Billing Cancellation",
        "id_fields": ["billingDocument"],
        "label_fields": ["billingDocument"],
        "detail_fields": ["billingDocumentType", "accountingDocument", "soldToParty", "totalNetAmount"],
        "color": "#fb7185",
        "size": 24,
    },
    "journal_entry_items_accounts_receivable": {
        "entity": "Journal Entry",
        "id_fields": ["accountingDocument", "accountingDocumentItem"],
        "label_fields": ["accountingDocument"],
        "detail_fields": ["referenceDocument", "customer", "amountInTransactionCurrency", "transactionCurrency", "postingDate"],
        "color": "#111827",
        "size": 34,
    },
    "payments_accounts_receivable": {
        "entity": "Payment",
        "id_fields": ["clearingAccountingDocument", "accountingDocument"],
        "label_fields": ["clearingAccountingDocument"],
        "detail_fields": ["customer", "amountInTransactionCurrency", "transactionCurrency", "clearingDate"],
        "color": "#6b7280",
        "size": 28,
    },
    "business_partners": {
        "entity": "Customer",
        "id_fields": ["businessPartner"],
        "label_fields": ["businessPartnerName", "businessPartner"],
        "detail_fields": ["customer", "businessPartnerFullName", "industry"],
        "color": "#9333ea",
        "size": 38,
    },
    "business_partner_addresses": {
        "entity": "Customer Address",
        "id_fields": ["businessPartner", "addressId"],
        "label_fields": ["businessPartner", "cityName", "addressId"],
        "detail_fields": ["cityName", "region", "country", "postalCode", "streetName"],
        "color": "#8b5cf6",
        "size": 20,
    },
    "customer_company_assignments": {
        "entity": "Customer Company",
        "id_fields": ["customer", "companyCode"],
        "label_fields": ["customer", "companyCode"],
        "detail_fields": ["paymentTerms", "reconciliationAccount", "customerAccountGroup"],
        "color": "#7c3aed",
        "size": 24,
    },
    "customer_sales_area_assignments": {
        "entity": "Customer Sales Area",
        "id_fields": ["customer", "salesOrganization", "distributionChannel", "division"],
        "label_fields": ["customer", "salesOrganization", "distributionChannel"],
        "detail_fields": ["customerPaymentTerms", "incotermsClassification", "incotermsLocation1", "supplyingPlant"],
        "color": "#a855f7",
        "size": 24,
    },
    "products": {
        "entity": "Product",
        "id_fields": ["product"],
        "label_fields": ["product"],
        "detail_fields": ["productType", "productGroup", "baseUnit"],
        "color": "#f59e0b",
        "size": 24,
    },
    "product_descriptions": {
        "entity": "Product Description",
        "id_fields": ["product", "language"],
        "label_fields": ["productDescription", "product"],
        "detail_fields": ["product", "language"],
        "color": "#fbbf24",
        "size": 18,
    },
    "product_plants": {
        "entity": "Product Plant",
        "id_fields": ["product", "plant"],
        "label_fields": ["product", "plant"],
        "detail_fields": ["availabilityCheckType", "profitCenter", "mrpType"],
        "color": "#14b8a6",
        "size": 20,
    },
    "product_storage_locations": {
        "entity": "Product Storage",
        "id_fields": ["product", "plant", "storageLocation"],
        "label_fields": ["product", "plant", "storageLocation"],
        "detail_fields": ["storageLocation", "plant", "physicalInventoryBlockInd"],
        "color": "#22c55e",
        "size": 18,
    },
    "plants": {
        "entity": "Plant",
        "id_fields": ["plant"],
        "label_fields": ["plantName", "plant"],
        "detail_fields": ["plantCategory", "salesOrganization", "distributionChannel"],
        "color": "#10b981",
        "size": 28,
    },
}

SYNTHETIC_NODE_CONFIG: Dict[str, Dict[str, Any]] = {
    "product_groups": {
        "entity": "Product Group",
        "color": "#fb7185",
        "size": 30,
    },
}

INFERENCE_MAX_VALUES = 300
INFERENCE_MIN_OVERLAP = 4
INFERENCE_MIN_RATIO = 0.18
GRAPH_EDGE_LIMIT_PER_LINK = 2500
UI_EXCLUDED_ENTITIES = {"Product Storage"}
UI_DEFAULT_ENTITY_LIMIT = 260
UI_ENTITY_LIMITS: Dict[str, int] = {
    "Product Plant": 220,
}
UI_SYNTHETIC_LINKS: Sequence[Tuple[str, str, str]] = (
    ("product_groups", "products", "productGroup"),
    ("product_groups", "sales_order_items", "materialGroup"),
    ("sales_order_headers", "sales_order_schedule_lines", "salesOrder"),
    ("sales_order_items", "sales_order_schedule_lines", "salesOrderItem"),
)
UI_HUB_LAYOUTS: Dict[str, Dict[str, Any]] = {
    "customer": {
        "center": (-1380.0, 220.0),
        "arc": (120.0, 470.0),
        "x_scale": 1.18,
        "y_scale": 1.0,
        "tier_radius": {0: 0.0, 1: 116.0, 2: 204.0, 3: 304.0},
        "spokes": 18,
        "spoke_gap": 26.0,
    },
    "sales": {
        "center": (-220.0, 70.0),
        "arc": (150.0, 446.0),
        "x_scale": 1.06,
        "y_scale": 0.82,
        "tier_radius": {0: 0.0, 1: 98.0, 2: 182.0, 3: 270.0},
        "spokes": 20,
        "spoke_gap": 18.0,
    },
    "delivery": {
        "center": (930.0, 120.0),
        "arc": (168.0, 418.0),
        "x_scale": 1.02,
        "y_scale": 0.84,
        "tier_radius": {0: 0.0, 1: 92.0, 2: 170.0, 3: 248.0},
        "spokes": 16,
        "spoke_gap": 18.0,
    },
    "billing": {
        "center": (340.0, 980.0),
        "arc": (160.0, 406.0),
        "x_scale": 1.04,
        "y_scale": 0.84,
        "tier_radius": {0: 0.0, 1: 92.0, 2: 168.0, 3: 242.0},
        "spokes": 16,
        "spoke_gap": 18.0,
    },
    "finance": {
        "center": (980.0, 980.0),
        "arc": (186.0, 418.0),
        "x_scale": 1.0,
        "y_scale": 0.82,
        "tier_radius": {0: 0.0, 1: 86.0, 2: 156.0, 3: 228.0},
        "spokes": 12,
        "spoke_gap": 18.0,
    },
    "product": {
        "center": (-620.0, 860.0),
        "arc": (156.0, 398.0),
        "x_scale": 1.0,
        "y_scale": 0.82,
        "tier_radius": {0: 0.0, 1: 84.0, 2: 154.0, 3: 226.0},
        "spokes": 14,
        "spoke_gap": 18.0,
    },
    "supply": {
        "center": (1220.0, 820.0),
        "arc": (188.0, 406.0),
        "x_scale": 1.0,
        "y_scale": 0.82,
        "tier_radius": {0: 0.0, 1: 90.0, 2: 162.0, 3: 236.0},
        "spokes": 10,
        "spoke_gap": 18.0,
    },
    "other": {
        "center": (1460.0, -340.0),
        "arc": (132.0, 382.0),
        "x_scale": 1.0,
        "y_scale": 0.84,
        "tier_radius": {0: 0.0, 1: 88.0, 2: 160.0, 3: 232.0},
        "spokes": 10,
        "spoke_gap": 18.0,
    },
}
GENERIC_TOKENS = {"inr", "abcd", "pc", "rv", "f2", "or", "tan", "d"}
RELATED_TABLE_HINTS: Dict[str, Tuple[str, ...]] = {
    "salesorder": ("sales_order_headers",),
    "salesorderitem": ("sales_order_items",),
    "scheduleline": ("sales_order_schedule_lines",),
    "deliverydocument": ("outbound_delivery_headers",),
    "deliverydocumentitem": ("outbound_delivery_items",),
    "billingdocument": ("billing_document_headers", "billing_document_cancellations"),
    "billingdocumentitem": ("billing_document_items",),
    "accountingdocument": ("journal_entry_items_accounts_receivable", "billing_document_headers", "billing_document_cancellations"),
    "customer": ("business_partners",),
    "businesspartner": ("business_partners",),
    "businesspartnername": ("business_partners",),
    "soldtoparty": ("business_partners",),
    "materialgroup": ("product_groups",),
    "productgroup": ("product_groups",),
    "material": ("products",),
    "product": ("products",),
    "plant": ("plants",),
    "productionplant": ("plants",),
    "supplyingplant": ("plants",),
}
LOW_SIGNAL_JOIN_FIELDS = {
    "companycode",
    "transactioncurrency",
    "currency",
    "fiscalyear",
    "salesorganization",
    "distributionchannel",
    "division",
    "country",
    "region",
    "postalcode",
    "weightunit",
    "baseunit",
    "industrysector",
    "billingdocumenttype",
    "producttype",
}
HUB_ENTITY_GROUPS: Sequence[Tuple[str, Sequence[str]]] = (
    ("customer", ("Customer", "Customer Address", "Customer Sales Area", "Customer Company")),
    ("sales", ("Sales Order", "Sales Order Item", "Schedule Line")),
    ("delivery", ("Delivery", "Delivery Item")),
    ("billing", ("Billing Item", "Billing Document", "Billing Cancellation")),
    ("finance", ("Journal Entry", "Payment")),
    ("product", ("Product Group", "Product", "Product Description")),
    ("supply", ("Product Plant", "Plant")),
)
HUB_ENTITY_PRIORITY: Dict[str, int] = {
    "Customer": 0,
    "Customer Company": 1,
    "Customer Sales Area": 1,
    "Customer Address": 2,
    "Sales Order": 0,
    "Sales Order Item": 1,
    "Schedule Line": 2,
    "Delivery": 0,
    "Delivery Item": 1,
    "Billing Document": 0,
    "Billing Item": 1,
    "Billing Cancellation": 1,
    "Journal Entry": 0,
    "Payment": 1,
    "Product Group": 0,
    "Product": 1,
    "Product Description": 1,
    "Product Plant": 1,
    "Plant": 0,
}
FIXED_PROCESS_LINKS: Sequence[Dict[str, Any]] = (
    {
        "source_table": "business_partners",
        "source_field": "customer",
        "target_table": "customer_company_assignments",
        "target_field": "customer",
        "overlap_count": 0,
        "overlap_ratio": 1.0,
        "label": "customer",
    },
    {
        "source_table": "business_partners",
        "source_field": "businessPartner",
        "target_table": "business_partner_addresses",
        "target_field": "businessPartner",
        "overlap_count": 0,
        "overlap_ratio": 1.0,
        "label": "businessPartner",
    },
    {
        "source_table": "business_partners",
        "source_field": "customer",
        "target_table": "customer_sales_area_assignments",
        "target_field": "customer",
        "overlap_count": 0,
        "overlap_ratio": 1.0,
        "label": "customer",
    },
    {
        "source_table": "customer_sales_area_assignments",
        "source_field": "customer",
        "target_table": "customer_company_assignments",
        "target_field": "customer",
        "overlap_count": 0,
        "overlap_ratio": 1.0,
        "label": "customer",
    },
    {
        "source_table": "customer_sales_area_assignments",
        "source_field": "customer",
        "target_table": "sales_order_headers",
        "target_field": "soldToParty",
        "overlap_count": 0,
        "overlap_ratio": 1.0,
        "label": "customer -> soldToParty",
    },
    {
        "source_table": "customer_sales_area_assignments",
        "source_field": "customer",
        "target_table": "billing_document_headers",
        "target_field": "soldToParty",
        "overlap_count": 0,
        "overlap_ratio": 1.0,
        "label": "customer -> soldToParty",
    },
    {
        "source_table": "customer_sales_area_assignments",
        "source_field": "supplyingPlant",
        "target_table": "plants",
        "target_field": "plant",
        "overlap_count": 0,
        "overlap_ratio": 1.0,
        "label": "supplyingPlant -> plant",
    },
    {
        "source_table": "business_partners",
        "source_field": "customer",
        "target_table": "sales_order_headers",
        "target_field": "soldToParty",
        "overlap_count": 0,
        "overlap_ratio": 1.0,
        "label": "customer -> soldToParty",
    },
    {
        "source_table": "business_partners",
        "source_field": "customer",
        "target_table": "billing_document_headers",
        "target_field": "soldToParty",
        "overlap_count": 0,
        "overlap_ratio": 1.0,
        "label": "customer -> soldToParty",
    },
    {
        "source_table": "business_partners",
        "source_field": "customer",
        "target_table": "billing_document_cancellations",
        "target_field": "soldToParty",
        "overlap_count": 0,
        "overlap_ratio": 1.0,
        "label": "customer -> soldToParty",
    },
    {
        "source_table": "business_partners",
        "source_field": "customer",
        "target_table": "journal_entry_items_accounts_receivable",
        "target_field": "customer",
        "overlap_count": 0,
        "overlap_ratio": 1.0,
        "label": "customer",
    },
    {
        "source_table": "business_partners",
        "source_field": "customer",
        "target_table": "payments_accounts_receivable",
        "target_field": "customer",
        "overlap_count": 0,
        "overlap_ratio": 1.0,
        "label": "customer",
    },
    {
        "source_table": "sales_order_headers",
        "source_field": "salesOrder",
        "target_table": "sales_order_items",
        "target_field": "salesOrder",
        "overlap_count": 0,
        "overlap_ratio": 1.0,
        "label": "salesOrder",
    },
    {
        "source_table": "sales_order_headers",
        "source_field": "salesOrder",
        "target_table": "sales_order_schedule_lines",
        "target_field": "salesOrder",
        "overlap_count": 0,
        "overlap_ratio": 1.0,
        "label": "salesOrder",
    },
    {
        "source_table": "sales_order_items",
        "source_field": "salesOrder",
        "target_table": "sales_order_schedule_lines",
        "target_field": "salesOrder",
        "overlap_count": 0,
        "overlap_ratio": 1.0,
        "label": "salesOrder",
    },
    {
        "source_table": "sales_order_items",
        "source_field": "salesOrderItem",
        "target_table": "sales_order_schedule_lines",
        "target_field": "salesOrderItem",
        "overlap_count": 0,
        "overlap_ratio": 1.0,
        "label": "salesOrderItem",
    },
    {
        "source_table": "sales_order_headers",
        "source_field": "salesOrder",
        "target_table": "outbound_delivery_items",
        "target_field": "referenceSdDocument",
        "overlap_count": 0,
        "overlap_ratio": 1.0,
        "label": "salesOrder -> referenceSdDocument",
    },
    {
        "source_table": "outbound_delivery_headers",
        "source_field": "deliveryDocument",
        "target_table": "outbound_delivery_items",
        "target_field": "deliveryDocument",
        "overlap_count": 0,
        "overlap_ratio": 1.0,
        "label": "deliveryDocument",
    },
    {
        "source_table": "outbound_delivery_items",
        "source_field": "deliveryDocument",
        "target_table": "billing_document_items",
        "target_field": "referenceSdDocument",
        "overlap_count": 0,
        "overlap_ratio": 1.0,
        "label": "deliveryDocument -> referenceSdDocument",
    },
    {
        "source_table": "billing_document_headers",
        "source_field": "billingDocument",
        "target_table": "billing_document_items",
        "target_field": "billingDocument",
        "overlap_count": 0,
        "overlap_ratio": 1.0,
        "label": "billingDocument",
    },
    {
        "source_table": "billing_document_headers",
        "source_field": "accountingDocument",
        "target_table": "journal_entry_items_accounts_receivable",
        "target_field": "accountingDocument",
        "overlap_count": 0,
        "overlap_ratio": 1.0,
        "label": "accountingDocument",
    },
    {
        "source_table": "plants",
        "source_field": "plant",
        "target_table": "sales_order_items",
        "target_field": "productionPlant",
        "overlap_count": 0,
        "overlap_ratio": 1.0,
        "label": "plant -> productionPlant",
    },
    {
        "source_table": "plants",
        "source_field": "plant",
        "target_table": "outbound_delivery_items",
        "target_field": "plant",
        "overlap_count": 0,
        "overlap_ratio": 1.0,
        "label": "plant",
    },
    {
        "source_table": "products",
        "source_field": "product",
        "target_table": "sales_order_items",
        "target_field": "material",
        "overlap_count": 0,
        "overlap_ratio": 1.0,
        "label": "product -> material",
    },
    {
        "source_table": "products",
        "source_field": "product",
        "target_table": "billing_document_items",
        "target_field": "material",
        "overlap_count": 0,
        "overlap_ratio": 1.0,
        "label": "product -> material",
    },
    {
        "source_table": "products",
        "source_field": "product",
        "target_table": "product_descriptions",
        "target_field": "product",
        "overlap_count": 0,
        "overlap_ratio": 1.0,
        "label": "product",
    },
    {
        "source_table": "products",
        "source_field": "product",
        "target_table": "product_plants",
        "target_field": "product",
        "overlap_count": 0,
        "overlap_ratio": 1.0,
        "label": "product",
    },
    {
        "source_table": "products",
        "source_field": "product",
        "target_table": "product_storage_locations",
        "target_field": "product",
        "overlap_count": 0,
        "overlap_ratio": 1.0,
        "label": "product",
    },
    {
        "source_table": "billing_document_cancellations",
        "source_field": "billingDocument",
        "target_table": "billing_document_headers",
        "target_field": "billingDocument",
        "overlap_count": 0,
        "overlap_ratio": 1.0,
        "label": "billingDocument",
    },
    {
        "source_table": "billing_document_cancellations",
        "source_field": "accountingDocument",
        "target_table": "billing_document_headers",
        "target_field": "accountingDocument",
        "overlap_count": 0,
        "overlap_ratio": 1.0,
        "label": "accountingDocument",
    },
    {
        "source_table": "product_plants",
        "source_field": "plant",
        "target_table": "plants",
        "target_field": "plant",
        "overlap_count": 0,
        "overlap_ratio": 1.0,
        "label": "plant",
    },
    {
        "source_table": "product_storage_locations",
        "source_field": "plant",
        "target_table": "plants",
        "target_field": "plant",
        "overlap_count": 0,
        "overlap_ratio": 1.0,
        "label": "plant",
    },
    {
        "source_table": "product_storage_locations",
        "source_field": "storageLocation",
        "target_table": "sales_order_items",
        "target_field": "storageLocation",
        "overlap_count": 0,
        "overlap_ratio": 1.0,
        "label": "storageLocation",
    },
    {
        "source_table": "product_storage_locations",
        "source_field": "storageLocation",
        "target_table": "outbound_delivery_items",
        "target_field": "storageLocation",
        "overlap_count": 0,
        "overlap_ratio": 1.0,
        "label": "storageLocation",
    },
)

DOMAIN_KEYWORDS = {
    "order",
    "sales order",
    "sales",
    "delivery",
    "billing",
    "invoice",
    "journal",
    "payment",
    "customer",
    "sold-to",
    "plant",
    "product",
    "material",
    "schedule line",
    "business partner",
    "company code",
    "distribution channel",
    "shipping point",
    "accounting document",
    "billing document",
    "order to cash",
    "o2c",
}

FOCUS_REFERENCE_PHRASES = {
    "this",
    "this node",
    "this record",
    "this customer",
    "this order",
    "this sales order",
    "this delivery",
    "this billing",
    "this billing document",
    "this invoice",
    "this payment",
    "this journal",
    "about this",
    "about this node",
    "about this record",
    "details of this",
}

QUESTION_ENTITY_HINTS: Sequence[Tuple[str, str]] = (
    ("customer address", "Customer Address"),
    ("customer sales area", "Customer Sales Area"),
    ("customer company", "Customer Company"),
    ("sales order item", "Sales Order Item"),
    ("sales order", "Sales Order"),
    ("schedule line", "Schedule Line"),
    ("delivery item", "Delivery Item"),
    ("delivery", "Delivery"),
    ("billing item", "Billing Item"),
    ("billing document", "Billing Document"),
    ("billing", "Billing Document"),
    ("invoice", "Billing Document"),
    ("journal entry", "Journal Entry"),
    ("journal", "Journal Entry"),
    ("payment", "Payment"),
    ("product group", "Product Group"),
    ("group", "Product Group"),
    ("product description", "Product Description"),
    ("product plant", "Product Plant"),
    ("product storage", "Product Storage"),
    ("product", "Product"),
    ("material", "Product"),
    ("plant", "Plant"),
)
