export const state = {
  cy: null,
  selectedNodeId: null,
  history: [],
  sessions: [],
  activeSessionId: null,
  entityGraph: new Map(),
  cardDrag: { active: false, startX: 0, startY: 0, originLeft: 0, originTop: 0 },
};

export const elements = {
  navToggleButton: document.getElementById("navToggleButton"),
  navMenu: document.getElementById("navMenu"),
  mappingSubmenu: document.getElementById("mappingSubmenu"),
  graphCanvas: document.getElementById("graphCanvas"),
  nodeCard: document.getElementById("nodeCard"),
  graphSection: document.querySelector(".graph-section"),
  hoverTooltip: document.getElementById("hoverTooltip"),
  nodeEntity: document.getElementById("nodeEntity"),
  nodeLabel: document.getElementById("nodeLabel"),
  nodeMeta: document.getElementById("nodeMeta"),
  nodeDetails: document.getElementById("nodeDetails"),
  askAboutNode: document.getElementById("askAboutNode"),
  closeNodeCard: document.getElementById("closeNodeCard"),
  messages: document.getElementById("messages"),
  promptInput: document.getElementById("promptInput"),
  sendButton: document.getElementById("sendButton"),
  statusBar: document.getElementById("statusBar"),
  focusBadge: document.getElementById("focusBadge"),
  historyPanel: document.getElementById("historyPanel"),
  historyList: document.getElementById("historyList"),
  closeHistoryButton: document.getElementById("closeHistoryButton"),
  fitButton: document.getElementById("fitButton"),
  resetButton: document.getElementById("resetButton"),
  zoomInButton: document.getElementById("zoomInButton"),
  zoomOutButton: document.getElementById("zoomOutButton"),
};
